### ISSUE TITLE
Improve user feedback if mapping with wildcard is defined for connector not supporting it

### ISSUE THREAD

**Issue by switschel** [Cumulocity-IoT/cumulocity-dynamic-mapper#270]
Currently if a mapping with wildcard is defined and a connector selected which doesn't support it no feedback is given to the user.
The only feedback is that the connector does not show up in the list even after the mapping is activated.

We could improve the feedback...
* by adding log entries to the microservice logs
* showing a error/warning in the UI if mapping is activated

As this is a limitation of MQTT service we would not invest much effort into this as it is a temporary issue until wildcards are supported by MQTT service.

**Comment by sagIoTPower** [comment]
![Screenshot 2024-10-02 at 20 48 18](https://github.com/user-attachments/assets/8e8c98fb-ffee-4a79-893e-ea62e5faf5fc)
A warning is added if the activation fails for a connectors.

This is included in: f37be3750d744c1af3d98cdf99c191960fa73f9f
