### ISSUE TITLE
Get Connectors request is called multiple times when refreshed

### ISSUE THREAD

**Issue by switschel** [Cumulocity-IoT/cumulocity-dynamic-mapper#277]
When hitting the refresh button in the connectors overview the GET connectors request is multiple times send which is unnecessary.

![image](https://github.com/user-attachments/assets/1507599e-cda3-420e-a1c3-65c835927118)

**Comment by ck-c8y** [comment]
This should be fixed with 6e1a67cd310d7083b690836eaee93a8ff706d050.
![Screenshot 2024-10-31 at 11 15 56](https://github.com/user-attachments/assets/4a3f0765-eacb-4ef0-b556-90f4519a39b1)
