### ISSUE TITLE
Topic Structure in Mapping Editor get lost

### ISSUE THREAD

**Issue by switschel** [Cumulocity-IoT/cumulocity-dynamic-mapper#278]
When you navigate back and forth in the templated & mappings steps in the UI and adding changing the templates, sometimes the Topic Structure disappears leading to errors in the Tests.

If you navigate back to the first step and click next the topic structure re-appears.

**Comment by ck-c8y** [comment]
@switschel: Could you pls. test if the bug is fixed in the current development branch.

Commit: e57f63d525c6d3b647eed797339c93d12dafaaf1

**Comment by switschel** [comment]
Still happening, but I can reproduce it now:
1. Navigate through the substitution page, switch to text editor
2. Navigate back to template page, switch to text editor

Topic Structure is disappeared

![image](https://github.com/user-attachments/assets/8580af97-7fd6-44c5-b643-09084468f02f)

**Comment by switschel** [comment]
Solved in develop branch
