### ISSUE TITLE
For Outbound Mappings the template are not updated

### ISSUE THREAD

**Issue by switschel** [Cumulocity-IoT/cumulocity-dynamic-mapper#279]
When creating an outbound mapping you can select an API. If you select one and click next you get template matching to the API.
If you get back and select another API the template sticks to the first selected API and shows warning:

![image](https://github.com/user-attachments/assets/2dd3679a-d4ea-48fe-ae74-ddb70910be85)

Expected behavior: Change template when selecting a different API.
Also not sure which impact "ALL" in the API has and how the default template should look like.

**Comment by ck-c8y** [comment]
@switschel : Can you pls. build and test the latest develop branch.

Changes for this fix are included in commit 4cdb56b36539d07863c89a1841cc9320a663ff97
